config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit]
  get 'home/index'
  root to: "home#index"
  resources :notes
  get 'tags/:tag', to: 'notes#index', as: :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :date, presence: true
  validates :instructor, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
  acts_as_taggable
  
  def previous
    Note.where(["id < ?", id]).last
  end
  
  def next
    Note.where(["id > ?", id]).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, 
  format: { with: VALID_EMAIL_REGEX }
  before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :log_partial_events
  helper_method :mobile?

  def log_partial_events
    @partial_events = []
    ActiveSupport::Notifications.subscribe("render_partial.action_view") do |event_name, start_at, end_at, id, payload|
    @partial_events << payload[:identifier]
    end
  end

  def after_sign_in_path_for(resource_or_scope)
    home_index_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def index
    @current_user = current_user
  end

  def edit
    @current_user = current_user
    @user = User.find(params[:id])
  end 

  protected

  def configure_permitted_parameters
    attributes = [:name, :training_since, :belt]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  private

  def mobile? # has to be in here because it has access to "request"
    request.user_agent =~ /\b(Android|iPhone|iPad|Windows Phone|Opera Mobi|Kindle|BackBerry|PlayBook)\b/i
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if not user_signed_in?
      redirect_to new_user_session_path
    end
    if user_signed_in?
      @current_user = current_user
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:edit, :update, :destroy, :show]

  def index
    @current_user = current_user
    if params[:tag]
      @user_notes = current_user.notes.tagged_with(params[:tag]).order(params[:sort])
    else
      @user_notes = current_user.notes.order(params[:sort])
    end
  end

  def new
    @note = Note.new
  end

  def create
   # render plain: params[:note].inspect\
   @note = Note.new(note_params)
   @note.user = current_user
   if @note.save
    flash[:notice] = "Note was successfully created"
    redirect_to notes_path
   else
    render 'new'
   end 
  end

  def edit
  end

  def update
    if @note.update(note_params)
     flash[:notice] = "Note was updated"
    #  redirect_to notes_path
    else
     flash[:notice] = "Note was not updated"
     render 'edit'
    end
  end

  def show
  end

  def destroy
    @note.destroy
    flash[:notice] = "Note was deleted"
    redirect_to notes_path
   end



  private

  def note_params
    params.require(:note).permit(:user_id, :title, :date, :instructor, :description, :tag_list)
  end

  def set_note
    @note = Note.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @new_user = User.new
  end

  def show
    @current_user = current_user
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/index.html.erb
<div class="note-show-container">
<%= render "shared/welcomebar" %>
<% if current_user.notes.any? %>
  <hr />
  <hr />
<%= render  "shared/recentnotes" %>
<% end %>
<hr />
<hr />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ClassNotes</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.typekit.net/upr7zlw.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>

<body>

  <% if user_signed_in? %>
  <%= render 'shared/navbar' %>
  <% end %>

  <main>
  <div class="routing-master">
    <p>Controller: <strong><%= controller_name %></strong></p>
    <p>Action: <strong><%= action_name %></strong></p>
    <p>Path: <strong><%= request.fullpath %></strong></p>
    <p>Partials: <p>
    <% @partial_events.map do |x| %>
      <p><strong><%= x.remove "/Users/arthurfincham/dev/personal/loginapp/app" %></strong></p>
    <% end %>
  </div>
  <%= yield %>
  </main>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
  </script>
</body>

</html>

app/views/notes/edit.html.erb
<%= render "shared/noteform" %>

app/views/notes/index.html.erb
<% if mobile?%>
<%= render  "shared/mobilenoteindex" %>
<% else %>
<%= render  "shared/noteindex" %>
<% end %>

app/views/notes/new.html.erb
<%= render  "shared/newnote" %>

app/views/notes/show.html.erb
<%= render  "shared/shownote" %>

app/views/shared/_errornotes.html.erb
<% if @note.errors.any? %>
  <div id="error_explanation">
      <% @note.errors.full_messages.each do |message| %>
    <div class="alert-alert<%= message %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
        <li><%= message %></li>
    </ul>
    </div>
      <% end %>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/shared/_mobilenoteindex.html.erb
<div class="note-show-container">
  <div class="note-show-box">
    <h1 class="table-title"><%= link_to 'All Notes', notes_path, method: :get %></h1>
    <div id="tag_cloud">
      <% tag_cloud @user_notes.tag_counts.order("tags.name"), %w[m] do |tag| %>
      <span
        class="badge badge-light"><%= link_to "#{tag.name.parameterize(separator: '_')}", tag_path(tag.name)%></span>
      <% end %>
    </div>
    <table class="table table-hover">
      <tr>
        <th><%= link_to "Note", :sort => "date DESC" %><i class="bi bi-arrow-down-up sort-arrows"></i></th>
        </th>
        <th>Description</th>
      </tr>
      <% @user_notes.each do |note| %>
      <tr class="row-index-hover">
        <td>
          <%= note.date.strftime("#{note.date.day.ordinalize} %b %y")%><br><strong><%= note.title %></strong><br><%= note.instructor %>
        </td>
        <td><%= link_to  "#{truncate(note.description, :length => 60, :separator => '')}", note_path(note) %></td>
  </div>
  </tr>
  <% end %>
  </table>
</div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href=<%= root_path %>>
    <%= image_tag "cn_logo.png", height: "50px" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to root_path, method: :get, class: 'nav-link' do %>
        <i class="bi bi-house" title="Home"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to notes_path, method: :get, class: 'nav-link' do %>
        <i class="bi bi-journal-text" title="All Notes"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_note_path, method: :get, class: 'nav-link' do %>
        <i class="bi bi-pen" title="New Note"></i>
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <i class="bi bi-person-lines-fill"></i>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Edit your profile', edit_user_registration_path(current_user), method: :get, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Sign In', new_user_session_path, class: 'nav-item' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Register', new_user_registration_path, class: 'nav-item' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_newnote.html.erb
<div class="note-show-container">
  <div class="note-edit-box">
    <%= render "shared/errornotes" %>
    <div class="note-preview-container">

      <div class="note-preview-box">
        <%= form_for @note do |f| %>
        <div class="stat-card-custom">
          <%= f.date_field :date, class: "note-preview-box-style" %>
        </div>
        <h2><%= f.text_field :title, placeholder: "Class Title", class: "note-preview-box-style" %></h2>
        <div class="stat-card-body">
          <p>
            <h3 id="tags_input"><%= f.text_field :tag_list, placeholder: "tags", class: "note-preview-box-style"%></h3>
          </p>
          <p>
            <h3><%= f.text_field :instructor, placeholder: "Instructor", class: "note-preview-box-style" %></h3>
          </p>
          <p class="note-show-text">
            <%= f.text_area :description, placeholder: "Description", class: "description-field note-preview-box-style" %>
          </p>
        </div>

        <div class="mt-2">
          <%= f.submit "Save", class: "w-25 btn btn-outline-dark btn-lg" %>
        </div>

      </div>
    </div>

    <% end %>

app/views/shared/_noteform.html.erb
<div class="note-show-container">
  <div class="note-edit-box">
    <%= render "shared/errornotes" %>
    <div class="note-preview-container">

      <div class="note-preview-box">
        <%= form_for @note do |f| %>
        <div class="stat-card-custom">
          <%= f.date_field :date, class: "note-preview-box-style" %>
        </div>
        <h2><%= f.text_field :title, placeholder: "Class Title", class: "note-preview-box-style" %></h2>
        <div class="stat-card-body">
          <p>
            <h3 id="tags_input"><%= f.text_field :tag_list, placeholder: "tags", class: "note-preview-box-style"%></h3>
          </p>
          <p>
            <h3><%= f.text_field :instructor, placeholder: "Instructor", class: "note-preview-box-style" %></h3>
          </p>
          <p class="note-show-text">
            <%= f.text_area :description, placeholder: "Description", class: "description-field note-preview-box-style" %>
          </p>
        </div>

        <div class="mt-2">
          <%= f.submit "Save changes", class: "w-25 btn btn-outline-dark btn-lg" %>
        </div>

        <td><%= link_to note_path(@note), method: :get do %>
          <i class="bi bi-eye" title="All Notes"></i>
          <% end %></td>

        <td><%= link_to note_path(@note), method: :delete, data: {confirm: "Are you sure?"} do %>
          <i class="bi bi-trash"></i>
          <% end %></td>
      </div>
    </div>

    <% end %>

app/views/shared/_noteindex.html.erb
<div class="note-show-container">
  <div class="note-show-box">
    <h1 class="table-title"><%= link_to 'All Notes', notes_path, method: :get %></h1>
    <div id="tag_cloud">
      <% tag_cloud @user_notes.tag_counts.order("tags.name"), %w[m] do |tag| %>
      <span class="badge badge-light"><%= link_to "#{tag.name.parameterize(separator: '_')
}", tag_path(tag.name)%></span>
      <% end %>
    </div>
    <table class="table table-hover">
      <tr>
        <th><%= link_to "Date", :sort => "date DESC" %><i class="bi bi-arrow-down-up sort-arrows"></i></th>
        <th><%= link_to "Title", :sort => "LOWER(title)" %><i class="bi bi-arrow-down-up sort-arrows"></i></th>
        <th><%= link_to "Instructor", :sort => "LOWER(instructor)" %><i class="bi bi-arrow-down-up sort-arrows"></i>
        </th>
        <th>Description</th>
      </tr>
      <% @user_notes.each do |note| %>
      <tr class="row-index-hover">
        <td><%= link_to "#{note.date.strftime("#{note.date.day.ordinalize} %B %Y")}", note_path(note) %></td>
        <td><%= link_to "#{note.title}", note_path(note) %></td>
        <td><%= link_to "#{note.instructor}", note_path(note) %></td>
        <td><%= link_to  "#{truncate(note.description, :length => 60, :separator => '')}", note_path(note) %></td>
  </div>
  </tr>
  <% end %>
  </table>
</div>
</div>

app/views/shared/_recentnotes.html.erb
<div class="note-show-container">
  <div class="note-show-box">
    <h1 class="table-title"><%= link_to 'Recent Notes', notes_path, method: :get %></h1>
    <table class="table table-hover">
      <% if mobile?%>
      <tr>
        <th><%= link_to "Note", :sort => "date DESC" %><i class="bi bi-arrow-down-up sort-arrows"></i></th>
        </th>
        <th>Description</th>
      </tr>
      <% else %>
      <tr>
        <th><%= link_to "Date", :sort => "date DESC" %><i class="bi bi-arrow-down-up sort-arrows"></i></th>
        <th><%= link_to "Title", :sort => "LOWER(title)" %><i class="bi bi-arrow-down-up sort-arrows"></i></th>
        <th><%= link_to "Instructor", :sort => "LOWER(instructor)" %><i class="bi bi-arrow-down-up sort-arrows"></i>
        </th>
        <th>Description</th>
      </tr>
      <% end %>
      <% if mobile? %>
      <% current_user.notes.last(5).each do |note| %>
      <tr class="row-index-hover">
        <td>
          <%= note.date.strftime("#{note.date.day.ordinalize} %b %y")%><br><strong><%= note.title %></strong><br><%= note.instructor %>
        </td>
        <td><%= link_to  "#{truncate(note.description, :length => 60, :separator => '')}", note_path(note) %></td>
  </div>
  </tr>
  <% end %>
  <% else %>
  <% current_user.notes.last(5).each do |note| %>
  <tr class="row-index-hover">
    <td><%= link_to "#{note.date.strftime("#{note.date.day.ordinalize} %B %Y")}", note_path(note) %></td>
    <td><%= link_to "#{note.title}", note_path(note) %></td>
    <td><%= link_to "#{note.instructor}", note_path(note) %></td>
    <td><%= link_to  "#{truncate(note.description, :length => 60, :separator => '')}", note_path(note) %></td>
</div>
</tr>
<% end %>
<% end %>
</table>
</div>
</div>

app/views/shared/_shownote.html.erb
<div class="note-show-container">
  <div class="note-edit-box">
    <%= render "shared/errornotes" %>
    <div class="note-preview-container">
      <div class="note-preview-box">
        <div class="stat-card-custom">
          <h2 class="note-preview-box-style"><%= @note.date.strftime("#{@note.date.day.ordinalize} %B %Y") %></h2>
        </div>
        <h2 class="note-preview-box-style"><%= @note.title %></h2>
        <div class="stat-card-body">
          <div id="tag_cloud">
            <% tag_cloud @note.tag_counts.order("tags.name"), %w[m] do |tag| %>
            <span
              class="badge badge-light"><%= link_to "#{tag.name.parameterize(separator: '_')}", tag_path(tag.name)%></span>
            <% end %>
          </div>
          <p>
            <h3 class="note-preview-box-style"><%= @note.instructor %></h3>
          </p>
          <p class="note-show-text"><%= @note.description %></p>
        </div>
        <div class="note-show-buttons">
          <% if @note.previous %>
          <%= link_to @note.previous do %>
          <i class="bi bi-arrow-left"></i>
          <% end %>
          <% end %>
          <%= link_to edit_note_url(@note), method: :get do %>
          <button type="button" class="btn btn-sm btn-outline-dark">EDIT</button>
          <% end %>
          <%= link_to note_path(@note), method: :delete, data: {confirm: "Are you sure?"} do %>
          <button type="button" class="btn btn-sm btn-outline-dark">DELETE</button>
          <% end %>
          <% if @note.next %>
          <%= link_to @note.next do %>
          <i class="bi bi-arrow-right"></i>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_welcomebar.html.erb
<h1><%= "Welcome #{current_user.name}" %></h1>
<div>
  <div class="home-buttons">
    <%= link_to notes_path, method: :get, class: 'nav-link home-nav-link' do %>
    <i class="bi bi-journal-text" title="All Notes"></i>
    <p>All Notes</p>
    <% end %>
    <%= link_to new_note_path, method: :get, class: 'nav-link home-nav-link' do %>
    <i class="bi bi-pen" title="New Note"></i>
    <p>New Note</p>
    <% end %>
  </div>
</div>

<h3 class="top-tags">Top Tags</h3>
<div id="tag_cloud">
  <% tag_cloud current_user.notes.tag_counts_on(:tags).limit(6), %w[m] do |tag| %>
  <span class="badge badge-light"><%= link_to "#{tag.name.parameterize(separator: '_')
}", tag_path(tag.name)%></span>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <div class="card p-3">
    <div class="d-flex align-items-center">
    <div class="image profile-pic-hue"> <img src="https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80" class="rounded" width="155"> </div>
            <div class="ml-3 w-100">
        <h4 class="mb-0 mt-0"><%= @current_user.name %><br></h4>
        <div class="spaced-text-card">
          <div class="d-flex flex-column"> <span class="articles"><%= @current_user.email %></span>
          <div class="d-flex flex-column"> <span class="articles">Belt: <%= @current_user.belt %></span>
          <div class="d-flex flex-column"> <span class="articles">Training since: <%= @current_user.training_since %></span>
          <div class="d-flex flex-column"> <span class="articles">Notes: <%= @current_user.notes.count %></span>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>